
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 09 17:51:47 CST 2023
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 2;
  public static final int PUNTO = 12;
  public static final int PUNTOYCOMA = 10;
  public static final int DOSPUNTOS = 11;
  public static final int OPERADOR_RELACIONAL = 17;
  public static final int ERROR = 22;
  public static final int VARIABLE = 20;
  public static final int OPERADOR_INCREMENTO = 14;
  public static final int COMILLAS = 9;
  public static final int CORCHETEAPERTURA = 7;
  public static final int LLAVECIERRE = 4;
  public static final int OPERADOR_POSITIVO = 15;
  public static final int OPERADOR_IGUAL = 16;
  public static final int EOF = 0;
  public static final int PARENTESISAPERTURA = 5;
  public static final int LLAVEAPERTURA = 3;
  public static final int NUMERO = 21;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 13;
  public static final int PARENTESISCIERRE = 6;
  public static final int TIPO_DATO = 18;
  public static final int CORCHETECIERRE = 8;
  public static final int RESERVADA = 19;
}

