package compilador;

/**
 * @author Julio M. Gomez Hernandez
 */
public enum Token {
    LINEA, LLAVEAPERTURA, LLAVECIERRE,
    PARENTESISAPERTURA, PARENTESISCIERRE, 
    CORCHETEAPERTURA, CORCHETECIERRE, COMILLAS, 
    PUNTOYCOMA, DOSPUNTOS, PUNTO, IDENTIFICADOR, 
    OPERADOR_INCREMENTO, OPERADOR_POSITIVO, 
    OPERADOR_IGUAL,OPERADOR_RELACIONAL, 
    TIPO_DATO, RESERVADA, VARIABLE, NUMERO,
    ERROR
}
